<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">


	   <xacro:rr_portal_bar name="z_frame_left"  width="${z_frame_bar_width}" len="${z_frame_bar_height}" height="${z_frame_bar_length}" weight="${z_frame_bar_weight}" />
       <xacro:rr_portal_bar name="z_frame_right" width="${z_frame_bar_width}" len="${z_frame_bar_height}" height="${z_frame_bar_length}" weight="${z_frame_bar_weight}" />
       
       <joint name="joint_z_frame_left_z_frame_right" type="fixed">
			<parent link="z_frame_left" />
			<child  link="z_frame_right" />
			<origin xyz="${x_axis_len+z_frame_bar_width} 0 0" rpy="0 0 0" />	
	   </joint>    

	   
	  <joint name="joint_y_axis" type="prismatic">
			<parent link="y_track_left" />
			<child  link="z_frame_left" />
			<origin xyz="0 0 ${z_axis_len/2 + y_track_height/2}" rpy="0 0 0" />	
		    <limit effort="1000.0" lower="-15" upper="15" velocity="30.0"/>
		    
      		<axis xyz="0 1 0"/>
      </joint>  
	   

	   
       	
</robot>
