<?xml version="1.0"?>
       			

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
xmlns:xacro="http://ros.org/wiki/xacro">
	


   <xacro:rr_portal_element name="z_slider"  x_size="${z_slider_width}" y_size="${z_slider_height}" z_size="${z_slider_len}" weight="${x_slider_weight}" />
   
    <joint name="joint_x_slider_z_axis" type="prismatic">
			<parent link="x_slider" />
			<child  link="z_slider" />
			<origin xyz="0 ${z_slider_height/2 + x_slider_len/2} 0" rpy="0 0 0" />	
		    <limit effort="1000.0" lower="-15" upper="15" velocity="30.0"/>
      		<axis xyz="0 0 1"/>
    </joint>  
	   
        
</robot>