<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:include filename="$(find rapid_robot_xacros)/defs/geometry/geo_ins.xacro"/>
<!-- Example -->
<!-- 
<xacro:rr_cam
	name             ="cam0"
	always_on        ="true"
	frame_name       ="camera0"
	image_width      ="640"
	image_height     ="480"
	image_format     ="R8G8B8"
	clip_near        ="0.02"
	clip_far         ="300"
	noise_type       ="gaussian"
	noise_mean       ="0.0"
	noise_std_dev    ="0.007"
	fov              ="0.873"
	hack_baseline    ="0.07"
	dist_K1          ="0.0"
	dist_K2          ="0.0"
	dist_K3          ="0.0"
	dist_T1          ="0.0"
	dist_T2          ="0.0"
	update_rate      ="30" 
	parent           ="base_link"
    has_inertia      ="false"
	>  
	<origin xyz="${chassis_len/2} 
                 0 
	             ${chassis_center}" rpy="0 0 0" />
	<geometry>
		<box size="0.02 0.02 0.02" />
	</geometry>
	<material name="Yellow">
		<color rgba="0 0 0 1"/>		
	</material>
	 <inertial/>
    </xacro:rr_cam>	 
	<xacro:rr_gaz_mat_s name="cam0" material="Gazebo/FlatBlack"/>
-->
			
<xacro:macro name="rr_cam" 
	params="
			name
			always_on
			frame_name
			image_width
			image_height
			image_format
			clip_near
			clip_far
			noise_type
			noise_mean
			noise_std_dev
			fov
			hack_baseline
			dist_K1
			dist_K2
			dist_K3
			dist_T1
			dist_T2
			update_rate
			parent
	        has_inertia 
		    *origin 
		    *geometry 
		    *material 
		    *inertial
	        ">
	
<xacro:rr_geo_ins/>
<gazebo reference="${name}_link">
	<material value="Gazebo/FlatBlack" />
	<sensor type="camera" name="${name}">
		<update_rate>${update_rate}</update_rate>
		<camera name="${name}_head">
			<horizontal_fov>${fov}</horizontal_fov>
			<image>
				<width>${image_width}</width>
				<height>${image_height}</height>
				<format>${image_format}</format>
			</image>
			<clip>
				<near>${clip_near}</near>
				<far>${clip_far}</far>
			</clip>
			<noise>
				<type>${noise_type}</type>
				<mean>${noise_mean}</mean>
				<stddev>${noise_std_dev}</stddev>
			</noise>
		</camera>
		<plugin name="camera_sensor" filename="libgazebo_ros_camera.so">
			<alwaysOn>${always_on}</alwaysOn>
			<updateRate>${update_rate}</updateRate>
			<cameraName>${name}</cameraName>
			<imageTopicName>image_raw</imageTopicName>
			<cameraInfoTopicName>camera_info</cameraInfoTopicName>
			<frameName>${frame_name}</frameName>
			<hackBaseline>${hack_baseline}</hackBaseline>
			<distortionK1>${dist_K1}</distortionK1>
			<distortionK2>${dist_K2}</distortionK2>
			<distortionK3>${dist_K3}</distortionK3>
			<distortionT1>${dist_T1}</distortionT1>
			<distortionT2>${dist_T2}</distortionT2>
		</plugin>
	</sensor>
</gazebo>
</xacro:macro>
</robot>
