<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro"
>
<!-- Example -->
<!--
<xacro:rplidar id="0"
	 	robot_namespace="${robot_namespace}"
		topic_name="/laser/scan"
		frame_name="laser"
		parent_link="chassis"
		x="0" 
        y="0" 
        z="${chassis_height/2}"
	    roll="0" 
	    pitch="0" 
        yaw="0" 
		update_rate="5.5"
		visualize="false" />	
-->
	
<xacro:include filename="$(find rapid_robot_xacros)/defs/constants.xacro"/>	
<xacro:macro name="rplidar" params="id
								robot_namespace
								topic_name
								frame_name
								parent_link
								x y z roll pitch yaw
								update_rate
								visualize
								">	
	
 <xacro:property />

  <!-- RPLidar Laser -->
  <link name="rplidar${id}_link">
    <collision>
      <origin xyz="0 0 ${0.098/2}" rpy="0 0 0"/>
      <geometry>
    	<box size="0.098 0.07 0.1" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${0.098/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.098 0.07 0.1" />
      </geometry>
	  <material name="Black">
		<color rgba="0 0 0 1"/>
	  </material>      

    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  
  <joint name="rplidar${id}_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}"/>
    <parent link="${parent_link}"/>
    <child link="rplidar${id}_link"/>
  </joint>
  
  
    <gazebo reference="rplidar${id}_link">
    <material value="Gazebo/FlatBlack" />
    <sensor type="gpu_ray" name="head_rplidar${id}_sensor">
      <visualize>${visualize}</visualize>
      <update_rate>${update_rate}</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>${2*const_pi}</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.20</min>
          <max>6.0</max>
          <resolution>0.005</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_rplidar${id}_controller" filename="libgazebo_ros_gpu_laser.so">
        <robotNamespace>${robot_namespace}</robotNamespace>
      	<topicName>${topic_name}</topicName>
        <frameName>rplidar${id}_link</frameName>
      </plugin>
    </sensor>
  </gazebo>
  
</xacro:macro>
</robot>