<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro" name="diff_drive_bot">
	
<xacro:include filename="$(find rapid_robot_xacros)/defs/rapid_robot.xacro"/>

	
<!-- Simple Robot Settings -->
<xacro:property name="chassis_height"          value="0.25"                            />
<xacro:property name="chassis_width"           value="${chassis_height*1.618}"         />  
<xacro:property name="chassis_len"             value="${chassis_width+chassis_height}" />
<xacro:property name="chassis_floor_clearance" value="${chassis_height/(1.618*2)}"     />

<xacro:property name="wheel_diameter"          value="${chassis_len/(1.618*1.618)}"    />  
<xacro:property name="wheel_width"             value="${chassis_width/(16.18)}"        />  
<xacro:property name="wheel_base_center_x"     value="${chassis_len/(-1.618*3)}"       />  
<xacro:property name="caster_collision_x"      value="${chassis_len/(1.618*2)}"        />
<xacro:property name="robot_namespace" value="/" />

<!--CHASSIS-->
<link name="chassis">
	 <xacro:rr_inertia_box_solid x="${chassis_len}" y="${chassis_width}" z="${chassis_height}" mass="1">
      <origin xyz="0 0 ${chassis_floor_clearance}" rpy="0 0 0" />
    </xacro:rr_inertia_box_solid>
	<visual>
		<geometry>
			<box size="${chassis_len} ${chassis_width} ${chassis_height}" />
		</geometry>
		<material name="Green">
			<color rgba="0 1 0 0.5"/>
		</material>
	</visual>
	<collision>
		<geometry>
			<box size="${chassis_len} ${chassis_width} ${chassis_height}" />
		</geometry>
		  	
	</collision>
</link>

<gazebo reference="chassis">
	<material value="Gazebo/Green"/>
</gazebo>

<!-- Bumper -->
<xacro:rr_bumper name="bumper0" parent="chassis" always_on="true" update_rate="30" topic="bumper0"  has_inertia="true">
	<origin xyz="${chassis_len/2} ${chassis_width/2} 0" rpy="0 0 0" />
	
	<geometry>
		<box size="0.02 0.02 ${chassis_height}" />
	</geometry>
	<material name="Black">
		<color rgba="0 0 0 1"/>		
	</material>
	 <xacro:rr_inertia_box_solid x="0.02" y="0.02" z="${chassis_height}" mass="0.1">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:rr_inertia_box_solid>
</xacro:rr_bumper>	
<gazebo reference="bumper0">
	<material value="Gazebo/FlatBlack" />
</gazebo>


<xacro:rr_bumper name="bumper1" parent="chassis" always_on="true" update_rate="30" topic="bumper0"  has_inertia="true">
	<origin xyz="${chassis_len/2} -${chassis_width/2} 0" rpy="0 0 0" />
	
	<geometry>
		<box size="0.02 0.02 ${chassis_height}" />
	</geometry>
	<material name="Black">
		<color rgba="0 0 0 1"/>		
	</material>
	 <xacro:inertia_box x="0.02" y="0.02" z="${chassis_height}" mass="0.1">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertia_box>
</xacro:rr_bumper>	
<gazebo reference="bumper1">
	<material value="Gazebo/FlatBlack" />
</gazebo>


<xacro:rr_bumper name="bumper2" parent="chassis" always_on="true" update_rate="30" topic="bumper0"  has_inertia="true">
	<origin xyz="${chassis_len/2} 0 -${chassis_height/4}" rpy="0 0 0" />
	
	<geometry>
		<box size="0.02 ${chassis_width-0.04} 0.02" />
	</geometry>
	<material name="Black">
		<color rgba="0 0 0 1"/>		
	</material>
	 <xacro:inertia_box x="0.02" y="0.02" z="0.04" mass="0.1">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertia_box>
</xacro:rr_bumper>	
<gazebo reference="bumper2"> 
	<material value="Gazebo/FlatBlack" />
</gazebo>



<!--CASTER -->
<link name="caster_collision">
	<visual>
		<geometry>
			<sphere radius="${chassis_floor_clearance}" />
		</geometry>
		<material name="Black">
			<color rgba="0 0 0 1"/>
		</material>
	</visual>
	<collision>
		<geometry>
			<sphere radius="${chassis_floor_clearance}" />
		</geometry>
	</collision>

    <inertial>
    <mass value="1.0"/>
    <origin xyz="0.0 0.0 0.0"/>
    <inertia ixx="0.1" 
             iyy="0.1" 
             izz="0.1"
        	 iyz="0.0"
             ixy="0.0" 
             ixz="0.0"/>
    </inertial>
</link>
<gazebo reference="caster_collision">
	<material value="Gazebo/FlatBlack"/>
</gazebo>
<joint name="base_caster_col_joint" type="fixed">
	<parent link="chassis" />
	<child link="caster_collision" />
	<origin xyz="${caster_collision_x} 0 ${-(chassis_height/2)}" rpy="0 0 0" />
</joint>





</robot>
											