<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

       	
<xacro:rr_gps_receiver
	name="gps0"
	reference_latitude="48.652726006"
	reference_longitude="9.184366555"
	reference_heading="0"
	reference_altitude="472.05"
	parent="base_link"
	has_inertia="false">
    <origin xyz="${-(chassis_len/2-0.04/2)-wheel_base_center_x} ${chassis_width/2-0.015} 
                 ${chassis_center_z+chassis_height/2+0.02/2}" 
                 rpy="0 0 0" />

		
	<geometry>
		<box size="0.02 0.02 0.02" />
	</geometry>
	<material name="Black">
		<color rgba="0 0 0 1"/>		
	</material>
	 <inertial/>
		
</xacro:rr_gps_receiver>
<xacro:rr_m_gz_black name="gps0"/>	
   
</robot>
