<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:property name="chassis_height" value="0.18" />
<xacro:property name="chassis_width" value="0.36" />  
<xacro:property name="chassis_len" value="0.56" />
<xacro:property name="chassis_floor_clearance" 
				value="0.07" />

<xacro:property name="wheel_diameter" value="0.23" />  
<xacro:property name="wheel_width" value="0.04" />  
<xacro:property name="wheel_base_center_x" value="-0.16" />  
<xacro:property name="caster_x" value="0.21"/>
<xacro:property name="chassis_center_z" 
				value="${chassis_floor_clearance+chassis_height/2}" />
<xacro:property name="wheel_separation" value="0.38" />  
</robot>