<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:property name="chassis_height" value="0.25" />
<xacro:property name="chassis_width" value="${chassis_height*1.618}" />  
<xacro:property name="chassis_len" value="${chassis_width+chassis_height}" />
<xacro:property name="chassis_floor_clearance" 
				value="${chassis_height/(1.618*2)}" />

<xacro:property name="wheel_diameter" value="${chassis_len/(1.618*1.618)}" />  
<xacro:property name="wheel_width" value="${chassis_width/(16.18)}" />  
<xacro:property name="wheel_base_center_x" value="${chassis_len/(-1.618*3)}" />  
<xacro:property name="caster_x" value="${chassis_len/(1.618*2)}"/>
<xacro:property name="chassis_center_z" 
				value="${chassis_floor_clearance+chassis_height/2}" />
<xacro:property name="wheel_separation" 
                value="0.38" />
</robot>