<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:rr_gps_receiver  
	name="gps0"
	frame_id="world"
	topic_name="fix"
	velocity_topic_name="fix_vel"
	reference_latitude="49"
	reference_longitude="8"
	reference_heading="0"
	reference_altitude="0"
	parent="base_link"
	has_inertia="true">
    <origin xyz="${-(chassis_len/2-0.04/2)-wheel_base_center_x} ${chassis_width/2-0.015} 
                 ${chassis_center_z+chassis_height/2+0.02/2}" 
                 rpy="0 0 0" />
	<geometry>
		<box size="0.04 0.03 0.02" />
	</geometry>
	<material name="Black">
		<color rgba="0 0 0 1"/>		
	</material>
	 <xacro:inertia_box x="0.02" y="0.02" z="0.04" mass="0.1">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertia_box>
</xacro:rr_gps_receiver>
<xacro:rr_gaz_mat_s name="gps0" material="Gazebo/FlatBlack"/>	
   
</robot>